---
title: "Movielens Prepare"
author: "Martin Kruger"
date: "02 September 2017"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Load data from csv and save as .Rdata  

```{r load_movielens}
rm(list=ls())

# read in the csv files
links <- read.csv("data/ml-latest-small/links.csv")
movies <- read.csv("data/ml-latest-small/movies.csv")
ratings <- read.csv("data/ml-latest-small/ratings.csv")
tags <- read.csv("data/ml-latest-small/tags.csv")

# save as .RData
save(links,movies,ratings,tags,file="data/movielens-small.RData")

# check that its worked
rm(list=ls())
load("data/movielens-small.RData")

```

## Prepare for recommender

```{r prep_movielens}

library(tidyverse)

# convert ratings to a "tibble"
ratings <- as.tibble(ratings)
print(ratings)

movies <- as.tibble(movies)
print(movies)

ratings <- left_join(ratings, movies)
head(ratings)


users_frq <- ratings %>% group_by(userId) %>% summarize(count = n()) %>% arrange(desc(count))
my_users <- users_frq$userId[101:115]
my_users


movies_frq <- ratings %>% group_by(movieId) %>% summarize(count = n()) %>% arrange(desc(count))
my_movies <- movies_frq$movieId[101:120]
my_movies


ratings_red <- ratings %>% filter(userId %in% my_users, movieId %in% my_movies) 
# and check there are 15 users and 20 movies in the reduced dataset
n_users <- length(unique(ratings_red$userId))
n_movies <- length(unique(ratings_red$movieId))
print(paste("number of users is",n_users))
print(paste("number of movies is",n_movies))
ratings_red


movies %>% filter(movieId %in% my_movies) %>% select(title)

ratings_red <- droplevels(ratings_red)
levels(ratings_red$title)


viewed_movies <- ratings_red %>% 
  select(userId,title,rating) %>% 
  complete(userId, title) %>% 
  mutate(seen = ifelse(is.na(rating),0,1)) %>% 
  select(userId,title,seen) %>% 
  spread(key = title, value = seen)
viewed_movies

save(ratings_red, viewed_movies, file = "output/recommender.RData")
```



